version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearchdev
    restart: always
    environment:
      - xpack.security.enabled=false 
      - discovery.type=single-node 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - els-data:/usr/share/elasticsearch/data
    ports:
      - 9299:9200
    expose:
      - 9299
  kibana:
    container_name: kibanadev
    image: docker.elastic.co/kibana/kibana:7.16.2
    restart: always
    #environment:    
    #  - SEVER_HOST=0.0.0.0
    #  - ELASTICSEARCH_HOSTS=http://elasticsearchdev:9299
    #  - xpack.security.enabled=false
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
volumes:
  els-data:
